name: ormed_postgres
description: PostgreSQL adapter for the routed ORM driver interface.
version: 0.1.0-dev+4
repository: https://github.com/RoutedDart/ormed
issue_tracker: https://github.com/RoutedDart/ormed/issues
documentation: https://ormed.vercel.app/
funding:
  - https://www.buymeacoffee.com/kingwill101
topics:
  - orm
  - database
  - postgres
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  ormed: ^0.1.0-dev+4
  postgres: ^3.5.9
  carbonized: ^0.1.0
  decimal: ^3.2.4
  uuid: ^4.5.2
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  driver_tests:
