name: artisanal
description: Artisanal-style command runner UX wrapper for package:args.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  acanthis: ^1.5.1
  args: ^2.7.0
  chalkdart: ^3.0.5
  path: ^1.9.1
  markdown: ^7.3.0
  characters: ^1.4.1
  image: ^4.7.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
