name: artisanal
description: A full-stack terminal toolkit for Dart featuring Lip Gloss styling, Bubble Tea TUI architecture, and Ultraviolet rendering.
version: 0.1.2
repository: https://github.com/RoutedDart/ormed
issue_tracker: https://github.com/RoutedDart/ormed/issues
documentation: https://ormed.vercel.app/
funding:
  - https://www.buymeacoffee.com/kingwill101
topics:
  - cli
  - tui
  - terminal
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  acanthis: ^1.5.1
  args: ^2.7.0
  chalkdart: ^3.0.5
  path: ^1.9.1
  markdown: ^7.3.0
  characters: ^1.4.1
  image: ^4.7.1
  html: ^0.15.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
