name: ormed_cli
description: Command-line tooling for the routed ORM (migrations generator & runner).
version: 0.1.0-dev+1
repository: https://github.com/RoutedDart/ormed
issue_tracker: https://github.com/RoutedDart/ormed/issues
documentation: https://ormed.vercel.app/
funding:
  - https://www.buymeacoffee.com/kingwill101
topics:
  - orm
  - cli
  - migrations
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  args: ^2.7.0
  artisanal: ^0.1.0-dev
  file: ^7.0.1
  meta: ^1.17.0
  path: ^1.9.1
  yaml: ^3.1.3
  ormed: ^0.1.0-dev
  ormed_sqlite: ^0.1.0-dev
  ormed_mysql: ^0.1.0-dev
  ormed_postgres: ^0.1.0-dev

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
executables:
  orm: orm
