name: ormed_cli
description: Command-line tooling for the routed ORM (migrations generator & runner).
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  file: ^7.0.1
  path: ^1.9.1
  yaml: ^3.1.3
  ormed:
  ormed_sqlite:
  ormed_mongo:
  ormed_mysql:
  ormed_postgres:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
executables:
  orm: orm
