name: _
publish_to: none
workspace:
  - packages/ormed
  - packages/driver_tests
  - packages/ormed_sqlite
  - packages/ormed_postgres
  - packages/ormed_mysql
  - packages/ormed_postgres_extensions
  - packages/ormed_cli
  - packages/artisanal
  - .site/examples

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.10.0 <4.0.0"
dependencies:
  contextual: ^2.0.0
  liquify: ^1.3.1
  path: ^1.9.1
  uuid: ^4.5.2
