name: _
publish_to: none
workspace:
  - packages/ormed
  - packages/driver_tests
  - packages/ormed_sqlite
  - packages/ormed_mongo
  - packages/ormed_postgres
  - packages/ormed_mysql
  - packages/ormed_cli
  - packages/orm_playground

funding:
  - https://www.buymeacoffee.com/kingwill101

environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  contextual: ^2.0.0
  liquify: ^1.3.1
  uuid: ^4.5.2
dependency_overrides:
  encrypt: ^5.0.3
  pointycastle: ^4.0.0
tags:
  - workspace
