name: orm_playground
description: A sample command-line application.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.10.0 <4.0.0"
resolution: workspace
# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  ormed: 0.1.0-dev
  ormed_sqlite: 0.1.0-dev
  ormed_cli: 0.1.0-dev
  artisanal: 0.1.0-dev

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  driver_tests:
