name: orm_playground
description: A sample command-line application.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.9.2
resolution: workspace
# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  ormed:
  ormed_sqlite:
  ormed_cli:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
  build_runner: ^2.10.3
