name: orm_playground
description: A sample command-line application.
version: 0.1.0-dev+6
publish_to: none
environment:
  sdk: ">=3.10.0 <4.0.0"
# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  ormed:
    path: ../ormed
  ormed_sqlite: ^0.1.0-dev+6
  ormed_cli: ^0.1.0-dev+6
  artisanal: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  driver_tests: ^0.1.0-dev+6


dependency_overrides:
  artisanal:
    path: ../artisanal
  ormed:
    path: ../ormed
  ormed_sqlite:
    path: ../ormed_sqlite
  ormed_cli:
    path: ../ormed_cli
  driver_tests:
    path: ../driver_tests
