name: ormed_analyzer
description: Analyzer plugin for Ormed query safety and raw SQL linting.
version: 0.1.0-dev+6
repository: https://github.com/RoutedDart/ormed
issue_tracker: https://github.com/RoutedDart/ormed/issues
documentation: https://ormed.vercel.app/
funding:
  - https://www.buymeacoffee.com/kingwill101
topics:
  - orm
  - analyzer
  - plugin
  - lint
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ^9.0.0
  analysis_server_plugin: ^0.3.4
  analyzer_plugin: ^0.13.11
  collection: ^1.19.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
  ormed: ^0.1.0-dev+6
  analyzer_testing: ^0.1.7
  test_reflective_loader: ^0.4.0
