name: ormed_sqlite
description: SQLite adapter for the routed ORM driver interface.
version: 0.1.0-dev
repository: https://github.com/routedart/routed
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  ormed:
  sqlite3: ^2.5.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.10.1
  test: ^1.25.6
  path: ^1.9.0
  driver_tests:
    path: ../driver_tests
