name: ormed_sqlite
description: SQLite adapter for the routed ORM driver interface.
version: 0.1.0-dev
repository: https://github.com/routedart/routed
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  ormed:
  sqlite3: ^3.1.0
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.10.4
  test: ^1.28.0
  driver_tests:
    path: ../driver_tests
