name: ormed_sqlite
description: SQLite adapter for the routed ORM driver interface.
version: 0.2.0
repository: https://github.com/RoutedDart/ormed
issue_tracker: https://github.com/RoutedDart/ormed/issues
documentation: https://ormed.vercel.app/
funding:
  - https://www.buymeacoffee.com/kingwill101
topics:
  - orm
  - database
  - sqlite
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  ormed: ^0.2.0
  ormed_sqlite_core: ^0.2.0
  sqlite3: ^3.1.1
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.10.4
  test: ^1.28.0
  driver_tests: ^0.2.0
