name: ormed
description: Strongly typed ORM core primitives (annotations, metadata, codecs, and generator) for the routed ecosystem.
version: 0.1.0-dev
repository: https://github.com/RoutedDart/ormed
resolution: workspace
environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  carbonized: ^0.1.0
  glob: ^2.1.3
  collection: ^1.19.1
  crypto: ^3.0.7
  yaml: ^3.1.3
  meta: ^1.17.0
  source_gen: ^4.1.1
  path: ^1.9.1
  test: ^1.28.0

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  ormed_sqlite: 0.1.0-dev
  driver_tests: 0.1.0-dev
  ormed_mysql: ^0.1.0-dev
  ormed_postgres: ^0.1.0-dev
