name: ormed
description: Strongly typed ORM core primitives (annotations, metadata, codecs, and generator) for the routed ecosystem.
version: 0.1.0
repository: https://github.com/RoutedDart/ormed
issue_tracker: https://github.com/RoutedDart/ormed/issues
documentation: https://ormed.vercel.app/
funding:
  - https://www.buymeacoffee.com/kingwill101
topics:
  - orm
  - database
  - sql
resolution: workspace
environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ^10.0.1
  analysis_server_plugin: ^0.3.7
  analyzer_plugin: ^0.14.1
  build: ^4.0.3
  carbonized: ^0.1.0
  decimal: ^3.2.4
  glob: ^2.1.3
  collection: ^1.19.1

  yaml: ^3.1.3
  dotenv: ^4.2.0
  meta: ^1.17.0
  source_gen: ^4.1.1
  path: ^1.9.1
  test: ^1.28.0
  contextual: ^2.1.0
  inflector_dart: ^1.0.2
  hashlib: ^2.3.0

dev_dependencies:
  analyzer_testing: ^0.1.9
  build_runner: ^2.10.4
  test_reflective_loader: ^0.4.0
  lints: ^6.0.0
  driver_tests: ^0.1.0
