name: ormed_fullstack_example
description: Full-stack movie catalog example using Ormed, Shelf, Liquify, and structured logging.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  artisanal: ^0.1.0
  contextual: ^2.0.0
  contextual_shelf: ^0.2.0
  file_cloud: ^0.1.0
  liquify: ^1.4.1
  ormed: ^0.1.0-dev+6
  ormed_cli: ^0.1.0-dev+6
  ormed_sqlite: ^0.1.0-dev+6
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  storage_fs: ^0.1.0

dev_dependencies:
  assertable_json: ^0.2.1
  build_runner: ^2.10.4
  http: ^1.6.0
  lints: ^6.0.0
  property_testing: ^0.2.1+1
  server_testing: ^0.2.0
  server_testing_shelf: ^0.2.1+1
  test: ^1.28.0

dependency_overrides:
  artisanal: { path: ../../../artisanal }
  ormed: { path: ../.. }
  ormed_cli: { path: ../../../ormed_cli }
  ormed_mysql: { path: ../../../ormed_mysql }
  ormed_postgres: { path: ../../../ormed_postgres }
  ormed_sqlite: { path: ../../../ormed_sqlite }
